import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1>Root Layout</h1><br/>
        <section>
          <nav>
            <ul>
              <li>
                <a href="/dashboard">Dashboard</a>
              </li>
              <li>
                <a href="/dashboard/settings">Settings</a>
              </li>
              <li>
                <a href="/dashboard/settings/test">Settings Test</a>
              </li>
              <li>
              <a className="bg-blue-400 px-4 py-2" href="/about">About</a>
            </li>
            </ul>
          </nav>
        </section><br/>
        <p>testing</p>
        {children}
      </body>
    </html>
  );
}
