import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import Toast Provider
import ToastProvider from "@/components/Providers/Toast";

// Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap the app content with Providers to include Toastify */}
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
