from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

# Create a router and register the PostViewSet
router = DefaultRouter()
router.register(r'posts', PostModelViewSet, basename='post')

urlpatterns = [
    path('', include(router.urls)),  # Include all routes generated by the router
]
